server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://139.99.121.54:3306/kilde_assignment?autoReconnect=true&useSSL=false'
    username: 'kilde_assignment'
    password: 'kilde_assignment'
  mvc:
    servlet:
      path: /api
      load-on-startup: 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database: mysql
    database-platform: com.senior.kilde.assignment.dao.dialect.MySQLDialect
    open-in-view: false
webui:
  servlet:
    load-on-startup: 1
    path: /*
  configuration-type: DEPLOYMENT
  wicket-factory: com.senior.kilde.assignment.web.factory.WicketFactory
  pages: com.senior.kilde.assignment.web.pages
  admin-lte: /opt/apps/github/ColorlibHQ/v3/AdminLTE
  csrf: false
logging:
  level:
    web: info
    sql: info